export const ADD_CHOSEN_COUNTRY = "ADD_CHOSEN_COUNTRY";
export const GET_COUNTRY_INFO = "GET_COUNTRY_INFO";
export const SET_CURRENT_CITY = "SET_CURRENT_CITY";
export const GET_CURRENT_CITY_INFO = "GET_CURRENT_CITY_INFO";
