export const FETCH_API_REQUEST = "FETCH_API_REQUEST";
export const FETCH_COUNTRIES_API_SUCCESS = "FETCH_COUNTRIES_API_SUCCESS";
export const FETCH_MAPS_API_SUCCESS = "FETCH_MAPS_API_SUCCESS";
export const FETCH_API_FAILURE = "FETCH_API_FAILURE";
export const FETCH_WEATHER_CURRENT_API_SUCCESS =
  "FETCH_WEATHER_CURRENT_API_SUCCESS";
export const FETCH_WEATHER_FORECAST_API_SUCCESS =
  "FETCH_WEATHER_FORECAST_API_SUCCESS";
export const TOGGLE_WEATHER_FORECAST_VIEW = "TOGGLE_WEATHER_FORECAST_VIEW";
export const FETCH_TICKETMASTER_API_SUCCESS = "FETCH__TICKETMASTER_API_SUCCESS";
